export const bankTypeOptions = [
  { label: "中国银行", value: "中国银行" },
  { label: "建设银行", value: "建设银行" },
  { label: "工商银行", value: "工商银行" },
  { label: "农业银行", value: "农业银行" },
  { label: "招商银行", value: "招商银行" },
  { label: "交通银行", value: "交通银行" },
  { label: "浦发银行", value: "浦发银行" },
  { label: "中信银行", value: "中信银行" },
  { label: "兴业银行", value: "兴业银行" },
  { label: "光大银行", value: "光大银行" },
  { label: "民生银行", value: "民生银行" },
  { label: "恒丰银行", value: "恒丰银行" },
  { label: "上海银行", value: "上海银行" },
  { label: "华夏银行", value: "华夏银行" },
  { label: "深圳发展银行", value: "深圳发展银行" },
];
